fn main() {
    foo()
}

fn foo() -> {
    x := 5
    if is_err(x) {
        println("no")
    }
}
